# Generated by Django 3.1.7 on 2021-03-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=30)),
                ('freelance', models.CharField(default='Available', max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
                ('skype', models.CharField(max_length=30)),
                ('languages', models.CharField(max_length=30)),
            ],
        ),
    ]
